// post-data.ts
export const postData = [
  {
    id: 1,
    title: 'Exploring Vue.js',
    content: 'Discover the power of Vue.js and its capabilities in modern web development.',
    imageUrl: 'https://vuejs.org/images/logo.png',
    date: '2023-11-20',
    author: 'Elijah Turner',
    category: 'Programming',
    tags: ['Vue.js', 'Web Development'],
  },
  {
    id: 2,
    title: 'JavaScript Best Practices',
    content: 'Master the best practices for writing clean and efficient JavaScript code.',
    imageUrl: 'https://i.ytimg.com/vi/hdI2bqOjy3c/maxresdefault.jpg',
    date: '2023-11-21',
    author: 'Scarlett White',
    category: 'Programming',
    tags: ['JavaScript', 'Coding'],
  },
  {
    id: 3,
    title: 'Deep Learning Applications',
    content: 'Explore real-world applications of deep learning and neural networks.',
    imageUrl: 'https://th.bing.com/th/id/OIP.1UX6Srd5GtN1qTmJPDDIBwHaDj?w=340&h=168&c=7&r=0&o=5&pid=1.7',
    date: '2023-11-22',
    author: 'Lucas Peterson',
    category: 'Machine Learning',
    tags: ['Deep Learning', 'Neural Networks'],
  },
  {
    id: 4,
    title: 'Web Development Trends 2023',
    content: 'Stay ahead of the curve with the latest trends and technologies in web development.',
    imageUrl: 'https://souluengineering.com/wp-content/uploads/2023/02/website-development-trends-in-2023.jpg',
    date: '2023-11-23',
    author: 'Grace Martin',
    category: 'Web Development',
    tags: ['Web Development', 'Trends'],
  },
  {
    id: 5,
    title: 'Python for Data Analysis',
    content: 'Learn how to analyze data effectively using Python and popular data analysis libraries.',
    imageUrl: 'https://th.bing.com/th/id/OIP.ZrDXhpI3EEmpc5ZINfGMvQAAAA?rs=1&pid=ImgDetMain',
    date: '2023-11-24',
    author: 'Caleb Roberts',
    category: 'Data Science',
    tags: ['Python', 'Data Analysis'],
  },
  {
    id: 6,
    title: 'Progressive Web Apps (PWAs)',
    content: 'Explore the concept of Progressive Web Apps and their advantages in modern web development.',
    imageUrl: 'https://th.bing.com/th/id/OIP.HaH1ouIjkZr-v1-rRsYrVQHaDg?rs=1&pid=ImgDetMain',
    date: '2023-11-25',
    author: 'Zoe Turner',
    category: 'Web Development',
    tags: ['PWAs', 'Web Apps'],
  },
  {
    id: 7,
    title: 'Machine Learning with TensorFlow',
    content: 'Dive into machine learning using TensorFlow and build powerful models.',
    imageUrl: 'https://www.tensorflow.org/images/tf_logo_social.png',
    date: '2023-11-26',
    author: 'Mason Phillips',
    category: 'Machine Learning',
    tags: ['TensorFlow', 'Machine Learning'],
  },
  {
    id: 8,
    title: 'CSS Grid Layout Techniques',
    content: 'Master the use of CSS Grid Layout for creating complex and responsive web layouts.',
    imageUrl: 'https://www.freecodecamp.org/news/content/images/2022/05/CSS-GRID-3.png',
    date: '2023-11-27',
    author: 'Ava Hill',
    category: 'Web Development',
    tags: ['CSS Grid', 'Responsive Design'],
  },
  {
    id: 9,
    title: 'Serverless Architecture Explained',
    content: 'Explore the concept of serverless architecture and its benefits in modern cloud computing.',
    imageUrl: 'https://th.bing.com/th/id/OIP.amK3bK6_ktpVw2nIm27PLgHaGK?rs=1&pid=ImgDetMain',
    date: '2023-11-28',
    author: 'Owen Rogers',
    category: 'Cloud Computing',
    tags: ['Serverless', 'Cloud'],
  },
  {
    id: 10,
    title: 'GraphQL and REST API Comparison',
    content: 'Compare the strengths and weaknesses of GraphQL and REST APIs for web development.',
    imageUrl: 'https://miro.medium.com/max/1200/1*jJZHFQmhkq_7ohn18KrMhA.png',
    date: '2023-11-29',
    author: 'Lily Perry',
    category: 'Web Development',
    tags: ['GraphQL', 'REST API'],
  },
];
